- name: checkout dotfiles
  ansible.builtin.git:
    repo: https://github.com/chkhetiani/dotfiles.git
    dest: /home/irakli/dotfiles
- name: stow it out
  shell: |
    stow -t /home/irakli -d /home/irakli/dotfiles -v * --adopt
    git -C /home/irakli/dotfiles/ restore .
