- name: is dofiles installed?
  stat:
    path: /home/irakli/.cfg
  register: dotfiles_exists
- name: clone bare dotfiles
  shell: |
    git clone --bare git@github.com:chkhetiani/.dotfiles.git $HOME/.cfg
    /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
    /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
  when: dotfiles_exists.stat.exists == False


