- name: clone bare dotfiles
  shell: git clone --bare git@github.com:chkhetiani/.dotfiles.git $HOME/.cfg
- name: set alias
  shell: alias config=''
- name: checkout content
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
- name: hide untrack configs
  shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no


